// <auto-generated />
namespace DefibrilatorProject.DataLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201503100739067_ProductModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
