// <auto-generated />
namespace DefibrilatorProject.DataLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProp));
        
        string IMigrationMetadata.Id
        {
            get { return "201503072300239_AddProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
